version: '3'

services:
  bet-app:
    image: bet:1.0.0-alpine3.21
    restart: always
    container_name: bet-1.0.0
    ports:
      - "9010:9000"
    environment:
      DB_HOST: postgres14
      DB_PORT: 5432
      DB_NAME: YOUR-db-name
      DB_USER: postgres
      DB_PASSWORD: YOUR-password
    depends_on:
      - postgres14
  postgres14:
    image: postgres:14.15-alpine3.21
    restart: always
    container_name: postgres-14.15
    ports:
      - "5432:5432"
    volumes:
      - "YOUR-db_path_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: YOUR-password
      PGDATA: /var/lib/postgresql/data/pgdata
